new_project/urls.py
from django.contrib import admin
from django.urls import path, include
from new_website import views

urlpatterns = [
    path('',include('new_website.urls'),name='index'),
    path('admin/', admin.site.urls),
    path('base/',include('new_website.urls')),
    path('register/',include('new_website.urls')),
    path ('login/', include('new_website.urls')),
    path('logout/',include('new_website.urls')),
    path('user_login/', include('new_website.urls')),
]

new_website/urls.py
from django.conf.urls import url
from new_website import views
from django.urls import path

##TEMPLATE TAGGING
app_name = 'new_website'

urlpatterns=[
    path('',views.index,name='index'),
    path('base/', views.base, name='base'),
    path('register/',views.register, name='register'),
    path('logout/',views.user_logout, name='logout'),
    path('user_login/',views.user_login,name="user_login"),
    # path('login/',views.login,name='login')
]

new_website/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)


    #additional 
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile-pics',blank=True)

    def __str__(self):
        return self.user.username

new_website/forms.py
from django import forms
from django.contrib.auth.models import User
from new_website.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProFileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

new_website/views.py
from django.shortcuts import render
from new_website.forms import UserForm, UserProFileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    context_dict = {'text': 'hello world','number': 100}
    return render(request,'new_website/index.html',context_dict)

def other(request):
    return render(request,'new_website/other.html')

def relative(request):
    return render(request, 'new_website/relative_templates.html')

def base(request):
    return render(request, 'new_website/base.html')

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProFileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProFileInfoForm()

    return render(request, 'new_website/registration.html',
                            {'user_form': user_form,
                            'profile_form': profile_form,
                            'registered': registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('new_website/index.html'))

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('new_website/index.html'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse ("Invalid login details supplied")
        
    else:
        return render(request,'new_website/login.html')

templates/new_website/base.html
<!DOCTYPE html>
<html>

<head>
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<h1>Welcome to Base</h1>
<body>
<nav class=navbar navbar-default navbar-static-top>
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-link" href="{% url 'new_website:index' %}">DJANGO</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'new_website:register' %}">Register</a></li>

            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{%url 'new_website:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'new_website:user_login' %}"></a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">

    {% block body_block %}
    <!-- Anything outside of this will be inherited -->
    {% endblock %}
</div>

</body>

</html>

templates/new_website/index.html
<!DOCTYPE html>
{% extends "new_website/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

<!-- <h1>{{ text|upper }}</h1>
<h1>{{ number|add:"99" }}</h1> -->
{% endblock %}
 

templates/new_website/login.html
{% extends 'new_website/base.html'%}
{% block body_block %}

<div class="jumbotron">

    <h1>Please login</h1>

    <form action="{% url 'new_website:user_login' %}">
        {%csrf_token%}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">
        
        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" name="Submit" value="Login">
    </form>

</div>
{% endblock %}

templates/new_website/other.html
<!DOCTYPE html>
{% extends "new_website/base.html" %}
{% block body_block%}
  <h1>Welcome to Other</h1>
  <h2>This is an example of template inheritance</h2>
{% endblock %}

templates/new_website/registration.html
{% extends 'new_website/base.html' %}
{% load staticfiles %}

{% block body_block%}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for your registration!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="POST"> 
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p}}

            <input type="submit" name="" value="Register">
            
        </form>
    {% endif %}


</div>

{% endblock %}

templates/new_website/relative_templates.html
<!DOCTYPE html>
<html>
    <head>
        <title>Relative Page</title>
    </head>
    <body>
        <h1>Welcome to Relative</h1>
        <a href="{% url 'new_website:other' %}">THE ORDER PAGE</a>
        <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    </body>
</html>